version: '3.5'

services:
  zookeeper:
    container_name: kafka-zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    env_file:
      - .env.zookeeper
    environment:
      KAFKA_HEAP_OPTS: -Xmx128m -Xms128m
    ports:
      - '0.0.0.0:2181:2181'
    volumes:
      - ../Volumes/kafka/zookeeper-data:/var/lib/zookeeper/data
      - ../Volumes/kafka/zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - kafka-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '2181']
      interval: 300s
      timeout: 3s
      retries: 3
      start_period: 30s
      start_interval: 5s

  kafka:
    container_name: kafka-broker
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      zookeeper:
        condition: service_healthy
    env_file:
      - .env.kafka
    environment:
      KAFKA_HEAP_OPTS: -Xmx512m -Xms512m
    ports:
      - '0.0.0.0:9092:9092'
      - '0.0.0.0:29092:29092'
    volumes:
      - ../Volumes/kafka/kafka-data:/var/lib/kafka/data
      - ../Volumes/kafka/kafka-logs:/opt/kafka/logs
    networks:
      - kafka-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 768M
        reservations:
          memory: 512M

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      kafka:
        condition: service_started
    ports:
      - '0.0.0.0:8080:8080'
    restart: always
    environment:
      JAVA_OPTS: -Xms64m -Xmx192m
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - kafka-net
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
        reservations:
          memory: 128M

networks:
  kafka-net:
    driver: bridge
    name: kafka-net
